title: Software System Analysis & Design
description: I'm Hiyoung Tsui, here is my course project about how to design a software.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
url: https://15331335.github.io/dev-sys # the base hostname & protocol for your site